import { createZip } from './zipUtils.js'
import { formatDate } from './routineGenerator.js'
import { PHASE_HEX } from './colors.js'

const INDIGO = '6366F1'
const HERO = '0F172A'
const INK = '334155'
const MUTED = '64748B'

const esc = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

function p(text, kind = '', color = '', fill = '') {
  const bold = kind === 'title' || kind === 'header'
  const size = kind === 'title' ? 32 : kind === 'header' ? 22 : 20
  const pPr =
    (kind === 'title' ? '<w:jc w:val="center"/><w:spacing w:after="200"/>' : '<w:spacing w:after="60"/>') +
    (fill ? `<w:shd w:val="clear" w:color="auto" w:fill="${fill}"/>` : '')
  const rPr = `${bold ? '<w:b/>' : ''}${color ? `<w:color w:val="${color}"/>` : ''}<w:sz w:val="${size}"/>`
  return `<w:p><w:pPr>${pPr}</w:pPr><w:r><w:rPr>${rPr}</w:rPr><w:t xml:space="preserve">${esc(text)}</w:t></w:r></w:p>`
}

const run = (t, b, c, s = 20) =>
  `<w:r><w:rPr>${b ? '<w:b/>' : ''}<w:color w:val="${c}"/><w:sz w:val="${s}"/></w:rPr><w:t xml:space="preserve">${esc(t)}</w:t></w:r>`

const pr = (runs) => `<w:p><w:pPr><w:spacing w:after="60"/></w:pPr>${runs}</w:p>`

function cell(text, opts = {}) {
  const { header = false, color = '', fill = '' } = opts
  const shd = fill ? `<w:shd w:val="clear" w:color="auto" w:fill="${fill}"/>` : ''
  return `<w:tc><w:tcPr><w:tcW w:w="0" w:type="auto"/>${shd}</w:tcPr>${p(
    text,
    header ? 'header' : '',
    color,
  )}</w:tc>`
}

const TR_H = '<w:trPr><w:trHeight w:val="480" w:hRule="atLeast"/></w:trPr>'

function row(cells, isHead) {
  const parts = cells.map((c) =>
    typeof c === 'string'
      ? cell(c, { header: isHead, color: isHead ? INDIGO : '', fill: isHead ? 'EEF2FF' : '' })
      : cell(c.t, c),
  )
  return `<w:tr>${TR_H}${parts.join('')}</w:tr>`
}
const BORDERS =
  '<w:tblBorders>' +
  ['top', 'left', 'bottom', 'right', 'insideH', 'insideV']
    .map((side) => `<w:${side} w:val="single" w:sz="4" w:space="0" w:color="999999"/>`)
    .join('') +
  '</w:tblBorders>'

function table(routine) {
  const head = row(['Date', 'Exam Type', 'Exam Name'], true)
  const body = routine.rows
    .map((r) => {
      const ph = PHASE_HEX[r.type]
      return row([
        { t: formatDate(r.date, true), fill: ph.bg, color: INK },
        { t: r.type, fill: ph.bg, color: ph.text },
        { t: r.title, fill: ph.bg, color: INK },
      ])
    })
    .join('')
  return `<w:tbl><w:tblPr><w:tblW w:w="5000" w:type="pct"/>${BORDERS}</w:tblPr>${head}${body}</w:tbl>`
}

const CONTENT_TYPES =
  '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>'

const RELS =
  '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'

export function buildDocx(routine) {
  const s = routine.stats
  const stats = pr(
    run('Total Exams ', true, MUTED) + run(`${s.total}   `, true, INDIGO, 24) +
      run('Paper Finals ', true, MUTED) + run(`${s.paperFinal}   `, true, PHASE_HEX['Paper Final'].text, 24) +
      run('Subject Finals ', true, MUTED) + run(`${s.subjectFinal}   `, true, PHASE_HEX['Subject Final'].text, 24) +
      run('Model Tests ', true, MUTED) + run(String(s.model), true, PHASE_HEX['Final Model Test'].text, 24),
  )
  const body = [
    p(routine.title || 'Exam Routine', 'title', 'FFFFFF', HERO),
    p(`Start Date: ${formatDate(routine.startDate, true)}`),
    p(`End Date: ${formatDate(routine.endDate, true)}`),
    stats,
    p(''),
    table(routine),
    p(''),
    p('Generated by Exam Center', '', MUTED),
  ].join('')
  const document = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134"/></w:sectPr></w:body></w:document>`
  return createZip([
    { name: '[Content_Types].xml', content: CONTENT_TYPES },
    { name: '_rels/.rels', content: RELS },
    { name: 'word/document.xml', content: document },
  ])
}
