import { formatDate } from './routineGenerator.js'
import { buildPdf } from './pdfBuilder.js'
import { buildDocx } from './docxBuilder.js'

const longDate = (iso) => formatDate(iso, true)
const SEP = '--------------------------------'

const fileBase = (routine) => {
  const name = (routine.title || 'Exam Routine').replace(/[\\/:*?"<>|]/g, '').trim()
  return name || 'Exam Routine'
}

function download(blob, filename) {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.click()
  URL.revokeObjectURL(url)
}

function metaLines(routine) {
  return [
    routine.title || 'Exam Routine',
    '',
    `Start Date: ${longDate(routine.startDate)}`,
    `End Date: ${longDate(routine.endDate)}`,
    `Total Exams: ${routine.stats.total}`,
    '',
    SEP,
    '',
  ]
}

function toMarkdown(routine) {
  const lines = metaLines(routine)
  lines.push('| Date | Exam Type | Exam Name |')
  lines.push('|------|-----------|-----------|')
  routine.rows.forEach((r) =>
    lines.push(`| ${longDate(r.date)} | ${r.type} | ${r.title} |`),
  )
  lines.push('', SEP, '', 'Generated by Exam Center')
  return lines.join('\n')
}

function toText(routine) {
  const lines = metaLines(routine)
  lines[0] = `==== ${lines[0]} ====`
  const w1 = 15
  const w2 = 17
  const pad = (s, n) => String(s).padEnd(n)
  lines.push(`${pad('Date', w1)}| ${pad('Exam Type', w2)}| Exam Name`)
  lines.push(`${'-'.repeat(w1)}|${'-'.repeat(w2 + 2)}|${'-'.repeat(20)}`)
  routine.rows.forEach((r) =>
    lines.push(`${pad(longDate(r.date), w1)}| ${pad(r.type, w2)}| ${r.title}`),
  )
  lines.push(SEP, '', 'Generated by Exam Center')
  return lines.join('\n')
}

export function exportMarkdown(routine) {
  download(new Blob([toMarkdown(routine)], { type: 'text/markdown;charset=utf-8' }), `${fileBase(routine)}.md`)
}

export function exportTxt(routine) {
  download(new Blob([toText(routine)], { type: 'text/plain;charset=utf-8' }), `${fileBase(routine)}.txt`)
}

export function exportPdf(routine) {
  download(buildPdf(routine), `${fileBase(routine)}.pdf`)
}

export function exportDocx(routine) {
  download(buildDocx(routine), `${fileBase(routine)}.docx`)
}
